### ISSUE TITLE
[Voice Chat] Last part of Voice assistance audio is getting trimmed

### ISSUE THREAD

**Issue by nitinmukesh** [SWivid/F5-TTS#288] opened 2024-10-26 17:25 UTC
![image](https://github.com/user-attachments/assets/6a2110e0-d2ef-4fb9-b5e9-b981a9e96cc8)

![image](https://github.com/user-attachments/assets/e9f8b10f-c218-406a-935e-220531b651de)

https://github.com/user-attachments/assets/fef936ee-8b01-4488-bc1e-be7812a336d2

**Comment by nitinmukesh** [comment] 2024-10-26 17:29
This issue is not always occurring. Here it is fine

![image](https://github.com/user-attachments/assets/478b35e2-6a60-443f-bfe6-36ade95c9f39)

**Comment by jpgallegoar** [comment] 2024-10-26 17:44
This is is an issue with the model itself, not specific with Voice Chat. The model especially struggles with numbers, since they are short (just one character) but have the sound of the actual number (four instead of 4). The model tries to predict the length of the output audio based on the tokens passed, so it under predicts the actual length. 

This will not happen if it writes the numbers as word, and is reproducible in the normal generation tab.

I will close the issue, feel free to open a new issue regarding the length of numerical tokens (which is the actual issue here) so it can be addressed appropriately.

**Closed by jpgallegoar** 2024-10-26 17:44 UTC
