### ISSUE TITLE
Buch of errors [Windows 10, Python 3.10]. final_wave = generated_waves[0], IndexError: list index out of range

### ISSUE THREAD

**Issue by kamineko16** [SWivid/F5-TTS#205] opened 2024-10-21 13:02 UTC
Hi, I did everything fine and still get errors. I tried reinstalling from zero 3 times, cuda is 11.8 and I have ffmpeg the latest version. I updated pip, I updated Anaconda. My GPU driver is updated. I'm using Windows 10. I also tried to purge the cache without results. I installed Python 3.10 in the environment.

At first, I thought it was a file issue, so I tried a bunch of different allowed formats, but after the second re-installation, I just tried the sample audio you provided and still got exactly the same errors. I installed all using the requirements file. I also tried on my last attempt to move the git folder from admin driver C to regular one E, didn't help. I tried to run it with administration rights and didn't help.

This is all the errors:
"
C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\transformers\models\whisper\generation_whisper.py:496: FutureWarning: The input name inputs is deprecated. Please make sure to use input_features instead.
  warnings.warn(
You have passed task=transcribe, but also have set forced_decoder_ids to [[1, None], [2, 50359]] which creates a conflict. forced_decoder_ids will be ignored in favor of task=transcribe.
C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\transformers\models\whisper\modeling_whisper.py:599: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Passing a tuple of past_key_values is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of EncoderDecoderCache instead, e.g. past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values).
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's attention_mask to obtain reliable results.
Traceback (most recent call last):
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\F5-TTS\gradio_app.py", line 66, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "E:\F5-TTS\model\utils_infer.py", line 214, in infer_process
    return infer_batch_process(
  File "E:\F5-TTS\model\utils_infer.py", line 307, in infer_batch_process
    final_wave = generated_waves[0]
IndexError: list index out of range
"

btw "generated_waves" is empty if it's important. I know it because, on my very first attempt, I was trying to use GPT, and it suggested printing "generated_waves" to check if it's really empty, so I just added a print line before the error and yes it was empty.

**Comment by SWivid** [comment] 2024-10-21 13:16
seems a failure with whisper asr pipeline.
have you tried with input manual the reference text for prompt audio?

**Comment by kamineko16** [comment] 2024-10-21 13:51
> seems a failure with whisper asr pipeline. have you tried with input manual the reference text for prompt audio?

Tried now, errors:
"
Traceback (most recent call last):
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\F5-TTS\gradio_app.py", line 66, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "E:\F5-TTS\model\utils_infer.py", line 214, in infer_process
    return infer_batch_process(
  File "E:\F5-TTS\model\utils_infer.py", line 307, in infer_batch_process
    final_wave = generated_waves[0]
IndexError: list index out of range
"

I tried using whisper manually, and it works fine. Gave me the text of the "country.flac" with 100% accuracy.

**Comment by kamineko16** [comment] 2024-10-21 15:09
> Hi @kamineko16 some possible solutions:
> 
> 1. try lower gradio version if >=5, `pip install gradio==4.44.1`
> 2. check for audio format, should with `pcm_s16le` e.g.. will have
>    ![image](https://private-user-images.githubusercontent.com/45333109/378474698-692dcba1-5a0f-4519-bb33-c6e763d47ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjI1NjIsIm5iZiI6MTcyOTUyMjI2MiwicGF0aCI6Ii80NTMzMzEwOS8zNzg0NzQ2OTgtNjkyZGNiYTEtNWEwZi00NTE5LWJiMzMtYzZlNzYzZDQ3YWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE0NTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0M2Y1ODc3MTkzNGMxNmRiZWQzY2UxNmY2Zjc4YTYyNWEyMzdjMjc0NjNjZDRhMWY2NjQyYTU2OGMyMmY5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vFacCMa3xzjE9eEwiBmCejhmJt_---HC5VqbDPuy29k)
>    visuals like this if successfully uploaded
> 3. maybe force re-pull the repo?

Hi @SWivid , answers to your suggestions:

1. It is already 4.44.1, so I guess it installed with the requirements as 4.44.1.

2. I used the sample from the F5-TTS sample folder, and I guess it is in the right format? However, I tried what you said anyway.
Here are pictures of both:
Original Flac file:
![Regular](https://github.com/user-attachments/assets/7284af58-61b2-4d79-8c0b-e8ab8d6098bb)

Same audio, but Wav file with pcm_s16le:
![pcm_s16le](https://github.com/user-attachments/assets/c1f93dcb-caea-4086-9959-0bd493e0c2f7)

Errors:
"
C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\transformers\models\whisper\generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50359]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\transformers\models\whisper\modeling_whisper.py:599: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Traceback (most recent call last):
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\{username}\anaconda3\envs\f5\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\F5-TTS\gradio_app.py", line 66, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "E:\F5-TTS\model\utils_infer.py", line 214, in infer_process
    return infer_batch_process(
  File "E:\F5-TTS\model\utils_infer.py", line 307, in infer_batch_process
    final_wave = generated_waves[0]
IndexError: list index out of range
"

3. I already tried it, when I said I reinstalled 3 times, what I meant was including the repo. I wiped out everything and downloaded everything again from zero 3 times. The last time was on drive E (current drive), in case it's an admin privilege issue, but it didn't help at all.

**Comment by SWivid** [comment] 2024-10-21 15:37
@kamineko16 it's very weird we haven't met this before, seems you're being the first one encountering this, sadge
will `inference-cli.py` work from your side?

**Comment by SWivid** [comment] 2024-10-21 16:32
Hi @kamineko16 , I have no idea of what's going wrong, as I could not reproduce the error.
You could just leave it open for somedays, see if someone also encounter this and are able to fix.

**Comment by superchargez** [comment] 2024-10-23 14:32
> > Hi @SWivid
> 
> @SWivid huh weird indeed, it's indeed working with inference-cli.py , so now I know everything is basically fine and the issue is with gradio_app.py ? Should I close this case or you want to check it more to understand why it's not working specifically with gradio_app.py ?

No. Problem is with whisper or transformer's pipeline. I have not tested on gradio, but my application is producing same warning. Though it generates output

**Comment by SWivid** [comment] 2024-10-25 22:04
will close this issue, feel free to open if further questions~

**Closed by SWivid** 2024-10-25 22:04 UTC

**Comment by marabian** [comment] 2024-12-02 23:18
Any fix for this? Facing same issue.

**Comment by kamineko16** [comment] 2024-12-02 23:23
> Any fix for this? Facing same issue.

Idk... I used the suggestion here which worked.

**Comment by marabian** [comment] 2024-12-02 23:24
@kamineko16 which suggestion? Using CLI?

**Comment by kamineko16** [comment] 2024-12-02 23:29
> @kamineko16 which suggestion? Using CLI?

Yep. I also gave gpt the cli code and regular code with the interface and asked it to combine them. GPT surprisingly managed to combine the two, to some degree, so you have cli with interface or whatever, but it worked.
