### ISSUE TITLE
Sometimes generates output with a phrase from reference audio.

### ISSUE THREAD

**Issue by chigkim** [SWivid/F5-TTS#85] opened 2024-10-15 02:15 UTC
The Ref_text includes the phrase 'our love of chocolate,' but the gen_text doesn't.
However, sometimes the phrase gets added to the end of a generation. When using inference-cli with long texts, it might repeat the phrase 2-3 times throughout.
It doesn't replace anything from the gen_text, just randomly adds it to end of some generations.
Any idea what might be causing this?

**Comment by SWivid** [comment] 2024-10-15 04:14
Mainly for unaccurate linearly estimated duration.
As it is leaking ref_text, consider just remove some punc in ref_text.
#11

**Comment by jpgallegoar** [comment] 2024-10-15 08:39
Try to always add a "." at the end of the reference text and begin the prompt with a " ". Also make sure the reference audio is properly trimmed (starts and ends in a silence and not during a sound), since that can also cause issues.

**Comment by chigkim** [comment] 2024-10-15 10:12
The ref_audio is recorded and edited well. There's no weird noise, nor cutoff phrases, etc.
@SWivid: "consider just remove some punc in ref_text."
@jpgallegoar "Try to always add a "." at the end of the reference text and begin the prompt with a " " ".
If it's just editing punctuations, should we make the script do this automatically?

**Comment by jpgallegoar** [comment] 2024-10-15 10:18
> The ref_audio is recorded and edited well. There's no weird noise, nor cutoff phrases, etc. @SWivid: "consider just remove some punc in ref_text." @jpgallegoar "Try to always add a "." at the end of the reference text and begin the prompt with a " ". If it's just editing punctuations, should we make the script do this automatically?

It's something I proposed but I'm not confident enough in that theory to create a PR and force it upon every generation. I also thought about passing the reference text and prompt to a small LLM with few-shot examples on how to accurately write everything to improve quality. This is still very early so we need to keep testing to find the best practices.

**Comment by chigkim** [comment] 2024-10-15 15:42
Since batch processing automatically splits long texts into smaller chunks, I think punctuation should be adjusted automatically because users can’t predict how the text will be split.
That said, I experimented with removing punctuation from the reference text and adding a space at the beginning and a period at the end of the generated text. Unfortunately, it didn’t seem to make much difference.
I experimented with various reference audios, and here are a couple of observations.
I'm not sure what it means, but the model seems to consistently selects the last phrase from the reference audio (never from the middle) and randomly inserts it.
E2 model seems to have this problem more so than F5.

**Comment by SWivid** [comment] 2024-10-15 15:52
@chigkim you are right. it is just an inherent problem exists in model that have no frame-level phoneme alignment - very sensitive to the given duration.
It is the last phrase leaked cuz model is going to synthesize e.g. abcdefg | 12345678 where alphabet is the ref_text and number is gen_text; after synthesizing speech, the part of the same length as ref_audio will be cut and discard.
So if the model is actually doing abcdef | g12345678, where abcdef is already the length of ref_audio, 'g' is leaked to output.
A just accurate duration will help avoiding such cases, and that's why in the initial script we are suggesting using a fixed duration (to control just as properly, though not quite convenient in actual usage scenario)
There will definitely be solution for this (as in past years we have seen big progress in TTS models)

**Comment by JarodMica** [comment] 2024-10-25 21:25
Interesting observation on my end, if you simply add 1-1.5 seconds of silence at the end of a reference sample, this issue kind of goes away and it sounds empirically better.  Unfortunately, when I preprocess datasets with whisper, I often get a lot of truncated audio samples.

No silence: https://vocaroo.com/1e6tZN4heFFW
![image](https://github.com/user-attachments/assets/35aa349a-0641-4a8a-999f-8f2c4f1f186c)


Silence added: https://vocaroo.com/1993kNqQlpMP
![image](https://github.com/user-attachments/assets/91d7b0d3-6f12-49f8-b1c5-1d389c827078)

**Comment by ajkessel** [comment] 2024-10-27 14:14
I've been seeing this too -- every 10 or 15 lines of generated audio have the last word from the reference audio added at the beginning.

**Comment by jpgallegoar** [comment] 2024-10-27 14:15
> I've been seeing this too -- every 10 or 15 lines of generated audio have the last word from the reference audio added at the beginning.

Make sure reference audio ends in ~1s of silence

**Comment by amoebatron** [comment] 2024-10-27 14:43
> > I've been seeing this too -- every 10 or 15 lines of generated audio have the last word from the reference audio added at the beginning.
> 
> Make sure reference audio ends in ~1s of silence

So to be clear, given that the reference audio is cropped to 15 seconds, you would need at most ~14 seconds of reference audio and 1 second of silence, rather than going beyond the 15 second limit yes?

**Comment by SWivid** [comment] 2024-10-27 14:48
> So to be clear, given that the reference audio is cropped to 15 seconds, you would need at most ~14 seconds of reference audio and 1 second of silence, rather than going beyond the 15 second limit yes?

Not that strict now, see
https://github.com/SWivid/F5-TTS/blob/1888fa49191b3c674db18dce3eb8c3bc58631e7c/src/f5_tts/infer/utils_infer.py#L185-L192
__________________
The current issue is, if you provide with a short ref_audio that will not be clipped, make sure there is a 1 sec silence at tail.

**Comment by ajkessel** [comment] 2024-10-27 17:42
The silence does seem to fix it. Is there any inference quality advantage to having a longer reference audio, or are we always better off with a shorter clip?

**Comment by jpgallegoar** [comment] 2024-10-27 18:13
> The silence does seem to fix it. Is there any inference quality advantage to having a longer reference audio, or are we always better off with a shorter clip?

As long as the reference audio is good quality, it's always better to make it as long as possible, so the model has more to learn from to mimic the voice.

**Comment by ajkessel** [comment] 2024-10-27 18:42
> > The silence does seem to fix it. Is there any inference quality advantage to having a longer reference audio, or are we always better off with a shorter clip?
> 
> As long as the reference audio is good quality, it's always better to make it as long as possible, so the model has more to learn from to mimic the voice.

Does a longer reference audio force you to shorten the length of the generated text for each batch? I thought that was a limitation but maybe it is not still the case?

**Comment by amoebatron** [comment] 2024-10-28 16:36
To me the issue is still persisting, even with multiple seconds of silence at the end. However it seems to be more of an issue with E2.

**Comment by ajkessel** [comment] 2024-10-29 14:08
Maybe better would be to do a clean cut at a silent point, and then add the 1-2 seconds of silence after that. There must be an optimal algorithm that will avoid the issue of the end of the prompt making it into the generated speech with the minimum necessary silence to avoid degrading quality.

**Comment by jpgallegoar** [comment] 2024-10-29 14:13
> Maybe better would be to do a clean cut at a silent point, and then add the 1-2 seconds of silence after that. There must be an optimal algorithm that will avoid the issue of the end of the prompt making it into the generated speech with the minimum necessary silence to avoid degrading quality.

Yes, that's something I've thought about. Another problem is that an audio's "silence" is never true silence, but when inserting silence, it would be actual silence, potentially leading to strange transitions in the generated audio. There is probably a way to generate a "silence" similar to the one present in the reference audio (including static, background noise, microphone artifacts, etc) which would yield better results. 

I might be over complicating stuff for no reason though.

**Comment by SWivid** [comment] 2024-10-29 15:19
currently we do like:
1. find for long silence and cut.
2. if no long silence, turn to find short one.
3. if all consistent speaking, rigid cut.

Thought best way is alway trimming manually as it is just easily feasible at gradio interface

**Comment by SWivid** [comment] 2024-11-22 07:27
will close this issue, feel free to open if further questions

**Closed by SWivid** 2024-11-22 07:27 UTC

**Comment by juangea** [comment] 2024-12-12 15:34
I still see this problem, many times words from the reference audio are included into the result, specially when we use fixed audio duration.

**Comment by jpgallegoar** [comment] 2024-12-12 15:40
> I still see this problem, many times words from the reference audio are included into the result, specially when we use fixed audio duration.

Precise audio duration is extremely important to generated audio quality. My spanish model can go from repeating words and mising others, to saying everything perfectly consistently just by changing the duration a bit. 

All of this is compounded with ref_text and ref_audio accuracy

**Comment by juangea** [comment] 2024-12-12 15:42
what do you mean with precise audio duration?

I have a reference audio, which I measure using the actual .wav duration, then I add the duration I require for the phrase, wich is pre-measured.

What do you mean with changing it a bit? adding or removing 0.1 seconds would be enough?

**Comment by jpgallegoar** [comment] 2024-12-12 15:44
> what do you mean with precise audio duration?
> 
> I have a reference audio, which I measure using the actual .wav duration, then I add the duration I require for the phrase, wich is pre-measured.
> 
> What do you mean with changing it a bit? adding or removing 0.1 seconds would be enough?

probably not 0.1s, but 1s or maybe even 0.5s yes. how are you calculating your duration required for the phrase? are you using the english model or another one?

**Comment by jpgallegoar** [comment] 2024-12-12 15:49
> I'm using an english model, the duration is computed because I'm using the original audio from another language to inject the same phrase with a different language in a video, so I have the timing from the original audio in a different language.
> 
> I will try performing a transcription after generation and then repeating the generation in case it's not correct and adding steps of 0.2 seconds to see if something changes.

But the time it takes to say a phrase in english is in no way similar to the time it takes to say that phrase translated to another language. You need to calculate it for real. What I did for example is create a linear interpolation model to calculate this duration for spanish phrases, using public datasets.

**Comment by juangea** [comment] 2024-12-12 16:04
Yeah, it’s not the exact same, but in the majority of cases it can be injected, I did it many times dubbing (truly dubbing personally) and it’s perfectly possible, in fact, in general it works, the phrases are actually correct, the problem are the words injected from the reference audio.

**Comment by jpgallegoar** [comment] 2024-12-12 16:08
> Yeah, it’s not the exact same, but in the majority of cases it can be injected, I did it many times dubbing (truly dubbing personally) and it’s perfectly possible, in fact, in general it works, the phrases are actually correct, the problem are the words injected from the reference audio.
> 
> what I will have to do is to transcribe the result and if it’s wrong cut it, it’s the only solution I can think of, if it does not work as it should.

All I can tell you is the quality of my generations improved drastically by using a proper calculated duration instead of the method that came with the repo.

**Comment by juangea** [comment] 2024-12-12 16:18
Where is the method?

where is in the repo?

for original generations could be great, for video dubbing we have to respect the original duration.

thanks for your comments BTW :)

**Comment by jpgallegoar** [comment] 2024-12-12 16:20
> Where is the method?
> 
> where is in the repo?
> 
> for original generations could be great, for video dubbing we have to respect the original duration.
> 
> thanks for your comments BTW :)

The repo is this one, the method is in infer_utils.py, search "predict". It's important to note that us humans can adapt our speech rate to match a time window, but this model is too sensitive for that. You are better off choosing other shorter / longer translations or slightly speeding the audio up or down to achieve this

**Comment by emptyngton** [comment] 2025-05-28 19:26
That's actually what helped me solve that issue.  ![Image](https://github.com/user-attachments/assets/eb9f3a31-8b1a-46b2-b980-13cdba569ac6)

**Comment by emptyngton** [comment] 2025-05-28 19:28
![Image](https://github.com/user-attachments/assets/f4f6f4ce-a710-4cc1-bdc8-072f9bd79330)
