### ISSUE TITLE
Trying to generate voice

### ISSUE THREAD

**Issue by Maenod** [SWivid/F5-TTS#388] opened 2024-11-04 06:48 UTC
### Checks

- [X] This template is only for usage issues encountered.
- [ ] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 10, Python 3.10

### Steps to Reproduce

1. Activate Conda env named f5 --> { conda activate f5 }
2. Run command "f5-tts_infer-gradio"
3. Opening the web, uploading voice, adding text
4. Clicking Synthesize

### ✔️ Expected Behavior

Should Generate a voice based on the provided text and uploaded voice.

### ❌ Actual Behavior

Keeping running for very long time and after that it generate audio without sound.
![1](https://github.com/user-attachments/assets/7a699a86-7f0b-42ab-b99f-222792858633)

Error Message :

Starting app...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
C:\ProgramData\miniconda3\envs\f5\lib\site-packages\transformers\models\whisper\generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
C:\ProgramData\miniconda3\envs\f5\lib\site-packages\transformers\models\whisper\modeling_whisper.py:545: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
gen_text 0 My name is Maen
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\maena\AppData\Local\Temp\jieba.cache
Loading model cost 0.631 seconds.
Prefix dict has been built successfully.

**Comment by SWivid** [comment] 2024-11-04 06:53
@Maenod Several possible solutions in #356 
Try first check network connection with huggingface,
then try 
https://github.com/SWivid/F5-TTS/blob/ac77a76cd3bc04c5aea12bd67980336433640f6a/src/f5_tts/infer/utils_infer.py#L131
https://github.com/SWivid/F5-TTS/blob/ac77a76cd3bc04c5aea12bd67980336433640f6a/src/f5_tts/infer/utils_infer.py#L144
`torch_dtype=torch.float32`
`model = model.to(torch.float32)`

**Comment by Maenod** [comment] 2024-11-04 07:11
When I tried to open the interface by using "f5-tts_infer-gradio" it give me error

Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

C:\Users\maena\Desktop\F5-TTS>conda activate f5

(f5) C:\Users\maena\Desktop\F5-TTS>f5-tts_infer-gradio
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\f5\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\envs\f5\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\envs\f5\Scripts\f5-tts_infer-gradio.exe\__main__.py", line 4, in <module>
    from f5_tts.infer.infer_gradio import main
  File "C:\Users\maena\Desktop\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 31, in <module>
    from f5_tts.infer.utils_infer import (
  File "C:\Users\maena\Desktop\F5-TTS\src\f5_tts\infer\utils_infer.py", line 131
    torch_dtype=torch.float32

SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by Maenod** [comment] 2024-11-04 07:12
> > I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
> 
> @Maenod Several possible solutions in #356 First check network connection with huggingface, then try
> 
> https://github.com/SWivid/F5-TTS/blob/ac77a76cd3bc04c5aea12bd67980336433640f6a/src/f5_tts/infer/utils_infer.py#L131
> 
> 
> https://github.com/SWivid/F5-TTS/blob/ac77a76cd3bc04c5aea12bd67980336433640f6a/src/f5_tts/infer/utils_infer.py#L144
> 
> 
> `torch_dtype=torch.float32`
> `model = model.to(torch.float32)`


When I tried to open the interface by using "f5-tts_infer-gradio" it give me error

Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

C:\Users\maena\Desktop\F5-TTS>conda activate f5

(f5) C:\Users\maena\Desktop\F5-TTS>f5-tts_infer-gradio
Traceback (most recent call last):
File "C:\ProgramData\miniconda3\envs\f5\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\ProgramData\miniconda3\envs\f5\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\ProgramData\miniconda3\envs\f5\Scripts\f5-tts_infer-gradio.exe_main.py", line 4, in
from f5_tts.infer.infer_gradio import main
File "C:\Users\maena\Desktop\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 31, in
from f5_tts.infer.utils_infer import (
File "C:\Users\maena\Desktop\F5-TTS\src\f5_tts\infer\utils_infer.py", line 131
torch_dtype=torch.float32

SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by SWivid** [comment] 2024-11-04 07:16
will close this issue as it's a duplicate of #356

**Closed by SWivid** 2024-11-04 07:16 UTC
Labels: help wanted
